name: Journey Tests

on:
  workflow_dispatch: # Manually trigger the suite
  workflow_call:     # Trigger it from another project
jobs:
  build:
    name: Journey Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Clone the test suite
        run: git clone --depth 1 https://github.com/DEFRA/cdp-node-journey-test-template.git .

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Setup the tests
        run: npm ci --omit=dev

      - name: Start docker compose
        run: docker compose up --wait-timeout 300 -d --quiet-pull

      - name: Run the tests
        run: npm test

      - name: debug
        if: failure()
        run: |
          docker ps
          # You can run commands like `docker logs service-name` here to help debug failures

      - name: cleanup
        if: always()
        run: docker compose down
